### ISSUE TITLE
The toilet icon is the same as for the water points

### ISSUE THREAD

**Issue by ravenfeld** [gpxstudio/gpx.studio#100]
I'm guessing a small problem in a mapping file but I don't know the language and can't do a PR.

**Comment by vcoppe** [comment]
It's not a mistake, there is currently no toilet icon in the library that I use, see https://github.com/lucide-icons/lucide/issues/1788. Hopefully it will be fixed soon.

**Comment by gorgobacka** [comment]
The icon should be included in the newest release: https://github.com/lucide-icons/lucide/releases/tag/0.460.0
