### ISSUE TITLE
Routing -- Load failed

### ISSUE THREAD

**Issue by kubasko** [gpxstudio/gpx.studio#108]
Hey,
I run your beautiful app on my server and encountered the issue with routing giving me the error "Load failed". See the following in js console:

"Fetch API cannot load https://routing.gpx.studio/?lonlats=21.05227292,52.19852724|21.05376259,52.19941516&profile=Trekking-dry&format=geojson&alternativeidx=0 due to access control checks."

In the readme you mentioned I need the mapbox token which i have but there is no information anything more is required. Is there any reason you calling https://routing.gpx.studio ?

thx
Jakub

**Comment by vcoppe** [comment]
It points to the [brouter](https://github.com/abrensch/brouter) instance used to compute the routes.
You can disable routing to test the website locally. Or you can follow the instructions on brouter's readme on how to launch your own instance.
