### ISSUE TITLE
Can't make overlay disappear

### ISSUE THREAD

**Issue by JasonEl1** [gpxstudio/gpx.studio#110]
I can't seem to make the overlay go away, either by using the "Toggle overlays" button or by unselecting all of the elements in settings. I would like to be able to make all overlay elements (parking spaces, restrooms, campgrounds) not appear on the map however I can't seem to do this.

**Comment by vcoppe** [comment]
You can toggle individual overlays and point-of-interest categories in the map layers control (see https://gpx.studio/help/map-controls).
In the map layer settings, you can select which layers appear in the map layers control.

**Comment by vcoppe** [comment]
To clarify this further, there are two dialogs:
- the map layers control on the right of the map, where you can add/remove layers to/from the map,
- the map layers settings, accessible by `Settings` -> `Map layers...`, where you can choose which layers will appear in the map layers control.

I just pushed a fix that automatically removes a layer from the map if it is disabled in the map layer settings. Before that, it was possible to hide a layer from the map layers control, and still have it on the map if it was added beforehand.

**Comment by JasonEl1** [comment]
Thanks for getting back to me. I think the overlay I was trying to get to disappear is actually just part of the MapBox Satellite basemap I was using. Thanks for the help.
