### ISSUE TITLE
[Feature Request] Expose 'comment' field in POI editing window 

### ISSUE THREAD

**Issue by rudose** [gpxstudio/gpx.studio#116]
The title is self-explanatory. I would like to request the addition of the 'comment' field in the POI editing window.

**Comment by vcoppe** [comment]
There is a single field called "Description" in the POI edition dialog, but its value is set to both the `<desc>` and `<cmt>` fields of the POI.
The idea being that most software or devices use only one of the two, but we rarely need to put something different in those two fields.

**Comment by rudose** [comment]
I wasn't aware of that. Unfortunately our software uses both fields, but I think we can adapt. And if generally only one of those is used, it's probably better to only use one of them anyway.
Thanks.
