### ISSUE TITLE
[Bug] Display issue in Brave@Android

### ISSUE THREAD

**Issue by opoto** [gpxstudio/gpx.studio#122]
Hi
The display is bad in Brave browser on Android: 
![Screenshot_20240929-235131](https://github.com/user-attachments/assets/96388ba6-5288-478b-87b9-7eb3bea7d09a)
Thanks

**Comment by vcoppe** [comment]
This is with the vertical file list enabled? (in the top menu: `View` > `Vertical file list`)
I agree that it's not rendering well on small screens but they are also not the target for this feature.

**Comment by opoto** [comment]
Yes indeed the vertical file list was checked. I don't remember having checked it.
When unchecked the map now properly covers the screen width.
I understand this feature is not compatible with such screen size (376x835). Maybe it should be disabled then? Or there should be a warning?
Anyway this is eventually not a bug, I close this issue.
Thanks!
