### ISSUE TITLE
[Bug] Re-routing is not triggered, when routing profile is changed

### ISSUE THREAD

**Issue by gorgobacka** [gpxstudio/gpx.studio#123]
(I discovered this platform a few days ago and directly used it to plan a few routes for the next month.
And it looks very promising. Thanks a lot. While doing to, I detected a few points that could be improved.)

When specified a route (e.g. start and end point), it's not possible to try different routing profiles, because the re-routing is only triggered, if a waypoint of the route is changed.

Proposed change: Re-routing is also triggered, when the routing profile is changed by the user.

**Comment by vcoppe** [comment]
This is the intended behavior. When creating a route, it can be useful to switch between multiple activities (or even disable routing) to get the desired output.

**Comment by gorgobacka** [comment]
Thanks for your reply. I wasn't aware that it is on purpose.
