### ISSUE TITLE
[Improvement] Open POI popup via click

### ISSUE THREAD

**Issue by gorgobacka** [gpxstudio/gpx.studio#125]
Usually, I have several POIs visible while planning my route but I don't want so see the details every time, when I have my mouse on the POI. This disturbs the experience while planning the details (specially in a crowded place with many POIs), because a large area of the map is not visible anymore (specially, if you arrange your route close by).

I would suggest that users have to click on a POI to show its details.

**Comment by vcoppe** [comment]
Thank you for this suggestion. I understand your point, but I think it also convenient not having to click on a POI to see its details, then click somewhere else to hide them.

So, for now, I will keep this as it is, but will think about it again if I receive other similar feedback.
