### ISSUE TITLE
[Feature Request] Use a POI to start or end a route

### ISSUE THREAD

**Issue by gorgobacka** [gpxstudio/gpx.studio#126]
It would be great to provide the user a way to use a POI as a start or end point of a route.

New options in the the POI popup:
- "Add as new start point"
- "Add as new end point"

(I would also like to see the option to add a POI as an intermediate waypoint. But this might be a bit more complicated to decide, between which existing waypoint it needs to be placed.)

**Comment by vcoppe** [comment]
This is an interesting proposition, but I feel like it would add a lot of complexity to the POI popup while not bringing so much value since you can simply manually click at the same location.
