### ISSUE TITLE
[Improvement] Change the popup for Mapillary images

### ISSUE THREAD

**Issue by gorgobacka** [gpxstudio/gpx.studio#127]
I really like that the site provides access to Mapillary, because it has a great coverage.

But it's currently difficult to plan a route while the Mapillary layer is activated, because popups open very often while moving the mouse over the map.

Two solutions that came to my mind:
* Put the image to the side (similar to the map view on www.mapillary.com)
or
* Open the image only on click

**Comment by vcoppe** [comment]
This is something I wanted to improve too. I have gone for a fixed location of the popup, and added a position and bearing marker to the map. Let me know what you think!

**Comment by gorgobacka** [comment]
@vcoppe Thanks a lot for considering this improvement and implementing it that fast. It looks very good.
