### ISSUE TITLE
[Feature Request] Detect surface data for imported files

### ISSUE THREAD

**Issue by gorgobacka** [gpxstudio/gpx.studio#128]
I detected myself and also read it in the documentation, that surface information is only available for files created with gpx.studio.

What's the reason for this limitation?

I expect, it's because an imported route do not correspond with road data.

If that's the case, I would like to request a feature to map a route to known roads (changes to the original route are allowed).
But I'm not exactly sure how to do this. Maybe by using several waypoints of the imported route and applying the brouter routing engine.

**Comment by vcoppe** [comment]
Surface data is part of the output of [brouter](https://github.com/abrensch/brouter), so it can easily be shown for files created on the website.

To have that for other files, the sequence of GPS coordinates should be snapped onto the OSM road network. There is an algorithm called [map matching](https://en.wikipedia.org/wiki/Map_matching) that does exactly that. Unfortunately, it is not implemented in brouter. But even if it was, it is computationally expensive (for example, there is a [Mapbox API](https://docs.mapbox.com/api/navigation/map-matching/) for this but limited to 100 coordinates) so further analysis would be needed.
