### ISSUE TITLE
[Bug] Application freezes when switching basemap

### ISSUE THREAD

**Issue by maperal** [gpxstudio/gpx.studio#129]
Today al issue started to happen when switching between basemaps. It happens both using the F1 key or using the drop-down menu on the right. Also, it is regardless of having a gpx file loaded or not.

I tested it in Chrome and Firefox (always using it in Firefox without issues). Tried to clean browser cache, storage, etc with no success.

The steps to reproduce it are:

- Load GPX studio with basemap "Mapbox Satellite":

![1_satellite](https://github.com/user-attachments/assets/bc3309bf-8a67-4a69-bb4f-8e9112be826a)

- Choose a file to load (optional).

- Switch the basemap to "Mapbox Outdoors" using F1 or the drop-down menu on the right:

![2_outdoors](https://github.com/user-attachments/assets/8f3ed7ef-8fad-4e61-92ea-460a6e12fb20)

- Switch back the basemap to "Mapbox Satellite", the basemap is not loaded, the map background turns blue and the applications does not respond:

![3_satellite](https://github.com/user-attachments/assets/edd66e58-aac6-4e69-b177-4896ed166196)

This app is amazing and I´m using it to plan a long distance trip, without it I wouldn't know how to do it.

**Comment by vcoppe** [comment]
I have tracked down the problem, and it's actually in Mapbox GL JS so I created an issue there (see https://github.com/mapbox/mapbox-gl-js/issues/13295).
In the meantime, I have added a temporary fix on my side.
