### ISSUE TITLE
Unable to edit routes using Firefox 128.0 on MacOS

### ISSUE THREAD

**Issue by b1tw153** [gpxstudio/gpx.studio#13]
If I create a new file in Firefox 128.0 on MacOS, the pencil tool is automatically enabled. However, the cursor on the map is still a hand and clicking on the map can only scroll it. Trying to add nodes to the route just doesn't work.

If I do the exact same thing on Safari, editing routes works just fine.

**Comment by vcoppe** [comment]
Can you check if there are any errors in the Javascript console?
I am changing things frequently at the moment so it could cause errors from one version to another.
You could verify this by clearing all browser data for gpx.studio and reloading.

**Comment by vcoppe** [comment]
> It seems to be working today.

Thanks, I am closing the issue but don't hesitate to comment on this issue if you encounter this problem again.

> `Error: The layer 'gpx-1-direction' does not exist in the map's style.`

That should be fixed now.
