### ISSUE TITLE
After major update OSM basemap is a bit blurry/unfocused

### ISSUE THREAD

**Issue by redmanmale** [gpxstudio/gpx.studio#135]
here is what OSM looks like, no scaling, as is:
![image](https://github.com/user-attachments/assets/3b9bec0c-b196-4db5-9fa5-2722b9cef997)

Mapbox Outdoors looks fine:
![image](https://github.com/user-attachments/assets/10e0cc3b-582c-4acb-baca-f0a955faed3c)

OpenHikingMap is blurry too:
![image](https://github.com/user-attachments/assets/5019acd9-bd3f-4037-b464-e435a33b629c)

Before major update/redesign OSM worked fine.
Tried different browsers, all is the same.

**Comment by vcoppe** [comment]
This is an unfortunate consequence of using the Mapbox GL JS map engine, which I didn't expect before making the switch. Some information about that can be found here: https://github.com/mapbox/mapbox-gl-js/issues/7771.

Mapbox GL JS is primarily designed to display vector-based data (like the Mapbox Outdoors basemap). Hopefully, the OSM basemap will soon be available in that format (see [this announcement](https://blog.openstreetmap.org/2024/02/11/2024-announcing-the-year-of-the-openstreetmap-vector-maps/)).

**Comment by redmanmale** [comment]
@vcoppe 
Sorry to bring it up again, but the bug you are refering to is closed as fixed years ago.

And the problem here is due to float zoom values because if I set zoom via URL to integers the map is crisp again:
[zoom = 11.38](https://gpx.studio/app#11.38/51.4966/-0.0787)
![Image](https://github.com/user-attachments/assets/600084cc-81e0-46b9-933e-46e62d5e2414)

[zoom = 11](https://gpx.studio/app#11/51.4966/-0.0787)
![Image](https://github.com/user-attachments/assets/3daeb13e-4c6f-441f-b235-2ccadd92b7b3)

**Comment by vcoppe** [comment]
That's what I had observed too. Still, there is nothing I can do about it since the map engine downsamples the tiles at fractional zoom levels.
