### ISSUE TITLE
[Improvement] add "elevation total" in elevation profile pop up

### ISSUE THREAD

**Issue by jbreizh** [gpxstudio/gpx.studio#137]
Hello,
now you can browse your track with the elevation profile.
The pop up give you the current elevation, distance and slope.
I could be nice to have the current elevation total on this pop up.
![gpxstudio](https://github.com/user-attachments/assets/9f074e4b-836b-442f-beee-d4d71f71a7e6)
Thanks for your work, killer app for MTB

**Comment by vcoppe** [comment]
Do you know that you can drag on the elevation profile to select a range? If you do it from the start up to any point, the stats of your selection are shown on the left of the profile.

**Comment by jbreizh** [comment]
Nope... so my "problem" is solve. Thanks for your time.
