### ISSUE TITLE
Map Layers Switzerland

### ISSUE THREAD

**Issue by N3XT191** [gpxstudio/gpx.studio#14]
Not sure if this is too specific to my personal use case and I can work around it by adding custom map layers, so you judge if this should be included or not:

Switzerland has 2 official map layers.

The Vector based one (which you have already included as a possible layer):

<img width="800" alt="Screenshot 2024-07-18 at 11 02 18" src="https://github.com/user-attachments/assets/cd85163c-5d18-480e-8c66-7c633d2f4bde">

The Raster based one (which is older and more well known):

<img width="1278" alt="Screenshot 2024-07-18 at 11 02 06" src="https://github.com/user-attachments/assets/ba7f7dc2-9127-479b-87c0-c73385187895">

I personally vastly prefer the second option for hike planning and navigation, so I would love to have this layer included as well. The URL for it is: https://wmts10.geo.admin.ch/1.0.0/ch.swisstopo.pixelkarte-farbe/default/current/3857/{z}/{x}/{y}.jpeg

Additionally, there is a layer available for marked Swiss hiking trails. As far as I can tell, they are all included in the existing Hiking Trail layer, but there they are mixed with other data. Additionally, the official Swiss layer displays the three "difficulty classes" in the appropriate colours: yellow, red and blue: (Both the hiking trail signposts as well as the paint-markings use these colours, so they are well-known by Swiss hikers)

<img width="1265" alt="Screenshot 2024-07-18 at 11 05 20" src="https://github.com/user-attachments/assets/a9726a34-2085-4732-99af-387d112270bb">

The URL is https://wmts10.geo.admin.ch/1.0.0/ch.swisstopo.swisstlm3d-wanderwege/default/current/3857/{z}/{x}/{y}.png

Third, there is a layer displaying the current hiking trail closures. I didn't manage to get it to work, since it seems to use a different protocol. The URL for a tile is the following

https://wms.geo.admin.ch/?REQUEST=GetMap&SERVICE=WMS&VERSION=1.3.0&FORMAT=image%2Fpng&STYLES=&TRANSPARENT=true&LAYERS=ch.astra.wanderland-sperrungen_umleitungen&LANG=en&CRS=EPSG%3A2056&WIDTH=752&HEIGHT=752&BBOX=2726000%2C1164480%2C2733520%2C1172000

I'm not sure if it's possible to include these kinds of layers.

You can try out the layers yourself here on map.geo.admin.ch: 

https://map.geo.admin.ch/#/map?lang=en&center=2725997.95,1165615.93&z=6.336&bgLayer=ch.swisstopo.pixelkarte-farbe&topic=ech&layers=ch.swisstopo.zeitreihen@year=1864,f;ch.bfs.gebaeude_wohnungs_register,f;ch.bav.haltestellen-oev,f;ch.swisstopo.swisstlm3d-wanderwege;ch.vbs.schiessanzeigen,f;ch.astra.wanderland-sperrungen_umleitungen

**Comment by vcoppe** [comment]
Done, as for the POIs, you might need to erase browser data for the website so that the layer collection is in sync.
If you want to add other layers in the future, you can look at this commit, follow the same steps and create a PR 😉

**Comment by N3XT191** [comment]
Damn, you're amazing! 


It seems like the order of overlays is determined by the order in which I set the checkboxes? 

I'd normally want to display the closures above the trails, but I can easily switch the order by removing and re-adding the closures so it doesn't really matter!

<img width="513" alt="Screenshot 2024-07-18 at 13 24 03" src="https://github.com/user-attachments/assets/578d092e-1ee7-4dd4-8fa8-de92ecb6ef85">

**Comment by vcoppe** [comment]
> It seems like the order of overlays is determined by the order in which I set the checkboxes?

Indeed, I think that doing it based on the order in the menu would not be flexible enough.
