### ISSUE TITLE
Ability to change start/end point of a round trip route

### ISSUE THREAD

**Issue by aphillips19** [gpxstudio/gpx.studio#142]
I frequently import GPX files found online for popular routes near me and customize them to my needs, instead of starting from scratch. They are usually round-trip routes that start/ somewhere convenient to the original creator, but not for me.

Given a round-trip route, I want to be able to move the start/end point to a new point along the route, and have gpx.studio adjust the waypoints so that the route otherwise does not change.

I haven't found a good way to do this yet. I can move every single waypoint around the map bit by bit (time-consuming and frustrating) or trace over the original route with my new one (less frustrating, but still time-consuming, and prone to errors). Alternatively, I can do this in komoot with their "[Change Start](https://support.komoot.com/hc/en-us/articles/360022829232-Changing-the-starting-point-of-a-Tour)" feature - making my changes then re-importing back into gpx.studio - but that service is of course not free.

P.S. Thanks so much for all the work you've done on this. It's made it so much easier to plan routes for any occasion, and I am a huge fan!

**Comment by vcoppe** [comment]
You can use the routing tool, and click on any point. If the start end end points of the route are sufficiently close, it will show a `Start loop here` button. See the [documentation](https://gpx.studio/help/toolbar/routing).
