### ISSUE TITLE
Too aggressive compression. Add more freedom.

### ISSUE THREAD

**Issue by snooppr** [gpxstudio/gpx.studio#150]
![1 cleaned](https://github.com/user-attachments/assets/55be25b4-1fa2-4ad5-bbf3-b0f9c6f3c71a)

I wanted to compress the track a little, but the compression settings for the track are too aggressive: the minimum compression by the algorithm is 95.5%. This is too aggressive. I tried the same compression algorithm described in the help in another software (GPSPrune) it offers compression from 1% and higher by the same algorithm.

Can you consider adjusting the compression algorithm more freely? For example, from 10% and higher.

Tried on a track (4 hours of recording).

**Comment by vcoppe** [comment]
Your screenshot shows the slider at the maximum compression level, which corresponds to the minimum tolerance. Have you tried increasing the value?

**Comment by snooppr** [comment]
You are confused. 
In the screenshot the slider is set (on the left) to the minimum compression: 687 points out of 15234. Moving the slider to the right increases the compression, and the maximum compression is 2 points out of 15234.

**Comment by vcoppe** [comment]
You're right, sorry.
Currently, the minimum tolerance used is 1 meter, meaning that the simplified line you get is never more than 1 meter away from your original line. What kind of precision would you need?

**Comment by snooppr** [comment]
Again, this is not true.
On the screen you see a simplified line with minimal compression = "0.001" It is assumed that this equals 1 meter. But this is a misconception. With such minimal compression of the track (I checked it on the track), the minimum distance between the points becomes 10 meters, sometimes 15 meters (the track was recorded ~1 point/second, i.e. point = 1m, after compression we get point = 10m).

**Comment by vcoppe** [comment]
I am not referring to the distance between consecutive points, but the distance between the line that connects consecutive points and points that were discarded by the simplification. Here is some information about the algorithm: https://en.wikipedia.org/wiki/Ramer%E2%80%93Douglas%E2%80%93Peucker_algorithm.

**Comment by snooppr** [comment]
![Без имени](https://github.com/user-attachments/assets/ce5a563d-a13f-4d2a-bb00-e4ae4eb94915)
Compression of the same track in GpsPrune (any tolerance).

I can't prove it any more. Try GpsPrune software, it can compress using the same algorithm, but you can set any compression tolerance, accordingly the track will be either smooth or straight (too big distance from point to point). In Gpxstudio the minimum compression is too aggressive and for example, if you compress a track faster than walking/running, for example, car or bike riding, then instead of a smooth track line you will get a rough one, because the distance between the points will be tens of meters.

**Comment by vcoppe** [comment]
Again, the *tolerance* (the parameter that you can adjust with the slider in gpx.studio) concerns the perpendicular distance between the simplified line and a point that does not belong to the simplified line. 

In the image below, you can see for step 1 that the current simplified line simply connects the two endpoints. We then take the point furthest away from this approximation: point *c*. And we compare the distance between the current approximation and this point, which is denoted *b* here. If this distance *b* is smaller than the tolerance, then it is not included in the simplified line.

![image](https://github.com/user-attachments/assets/a2bfc4fa-30bc-4908-8c66-3765a6b1de6a)
(from https://fr.wikipedia.org/wiki/Algorithme_de_Douglas-Peucker)

This means that there is no constraint on the distance between consecutive points in the output of the algorithm. If you have 1000 points in a straight line, and use this algorithm with any tolerance above 0, then you will always get the 2 extreme points in the output.

Therefore, I can either allow for even smaller tolerance values on the website, or propose another simplification algorithm.

**Comment by snooppr** [comment]
I'll express my opinion: adding new track compression algorithms is cool, but the complexity of development increases, it is enough to change the tolerance (extend the slider to the left).

**Comment by snooppr** [comment]
Great job, I just checked the compression on my last workout and the tolerance is much looser.
