### ISSUE TITLE
GPX points are aggregated when editing a track

### ISSUE THREAD

**Issue by WaterBread** [gpxstudio/gpx.studio#16]
### Current Behaviour

When editing a point a track, it appears to group points together and aggregates them to a single point. This affects the expected outcome, as areas where there is no movement (any many points in a cluster) get lost, distorting the timestamps.

Comparison of the behaviour in the old version and new:

[Screencast_20240720_095328.webm](https://github.com/user-attachments/assets/b515a0af-2a44-4b2f-86b7-05c9a9d57104)

The behaviour was a little odd in the original, but worked somewhat. The level of zoom dictated the grouping. When zoomed all the way in, it only moved some points, and moved many when zoomed out.

### Expected Behaviour

Ideally though, the behaviour would be to be additive, rather than destructive of the original GPX points. When dragging a space between two original points, it should add new points in between rather than moving the originals.

**Comment by WaterBread** [comment]
Actually - it does seem to have the same zoom behaviour, albeit a little more aggressive with how many points it wants to group and move.

[Screencast_20240720_101446.webm](https://github.com/user-attachments/assets/7eb08fc2-18a7-4ae8-83ae-7c8362411e81)

I think a toggle of "Preserve existing points" would be useful to ensure the behaviour is consistent.

**Comment by vcoppe** [comment]
I am pretty satisfied with the current anchor point logic (the amount shown with respect to the zoom level). However, I have just updated the parameters so that very high zoom levels are also covered. Now, you can edit your trace at high precision when fully zoomed in.
I hope this helps, otherwise feel free to describe what you would expect in more detail.
