### ISSUE TITLE
Menu for Point "Split Here"

### ISSUE THREAD

**Issue by Volodymyr-13** [gpxstudio/gpx.studio#20]
I really need this menu, since it's now so confusing and hard to just split tracks..

![Screenshot](https://github.com/user-attachments/assets/58785938-9dbb-477b-bd9f-c7b7bf6789de)

**Comment by vcoppe** [comment]
I have updated the scissors tool. In addition to clicking anywhere on the trace to split it there, I have added "split markers" at relevant locations (more or less of them are shown depending on the zoom level).

**Comment by Volodymyr-13** [comment]
> I have updated the scissors tool. In addition to clicking anywhere on the trace to split it there, I have added "split markers" at relevant locations (more or less of them are shown depending on the zoom level).

I’m not sure when it will be available but still not seeing this.

**Comment by vcoppe** [comment]
It's online since the last build.

**Comment by Volodymyr-13** [comment]
> It's online since the last build.

Have no idea what do you mean.. I'm expecting to see the menu as indicated in first post, like to just split in point. 
For now I just see a remove point menu.

**Comment by vcoppe** [comment]
You need to use the "scissors" tool...

**Comment by Volodymyr-13** [comment]
> You need to use the "scissors" tool...

I tried - clicked.. and nothing happening. I like more old way with right click menu like.
