### ISSUE TITLE
GPX track appearance not being imported

### ISSUE THREAD

**Issue by mikemills** [gpxstudio/gpx.studio#21]
Files are all opening as black paths. Is this just something you haven't got to yet?

**Comment by vcoppe** [comment]
Can you send me the files that you try to load? (here or at hello@gpx.studio)
Normally this is handled by the website but maybe your files encode this differently.

**Comment by mikemills** [comment]
I've tried a few of my files - all with the same result. The appearance on them was configured using GPX Studio and they work fine in the old app.

Some of them are here:

https://woodmills.github.io/Canberra-Walks/gpx/6.1%20–%20Stromlo%20Park%20to%20Cooleman%20Ridge.gpx
https://woodmills.github.io/Canberra-Walks/gpx/6.1a%20–%20Narrabundah%20Hill%20Reserve.gpx
https://woodmills.github.io/Canberra-Walks/gpx/6.2%20–%20Cooleman%20Ridge.gpx
https://woodmills.github.io/Canberra-Walks/gpx/6.3%20–%20Mount%20Arawang.gpx
https://woodmills.github.io/Canberra-Walks/gpx/6.4%20–%20McQuoids%20Bicentennial%20Trail.gpx
https://woodmills.github.io/Canberra-Walks/gpx/6.5%20–%20Kambah%20Pool,%20Urambi%20Hills%20Loop.gpx
https://woodmills.github.io/Canberra-Walks/gpx/6.6%20–%20Tuggeranong%20Town%20Centre%20loop.gpx
https://woodmills.github.io/Canberra-Walks/gpx/6.7%20–%20Pine%20Island%20and%20the%20Archery%20Club.gpx

They can also be accessed in Google drive here - https://drive.google.com/drive/folders/1BKdPD2FZJwLOEZaB_UNuOxf5ThZZHN2z?usp=sharing

**Comment by vcoppe** [comment]
My mistake, I forgot that colors are stored as hex values in GPX files <ins>but without the leading `#`</ins>.
