### ISSUE TITLE
"Orphaned" custom layer reference

### ISSUE THREAD

**Issue by pfbreton-perso** [gpxstudio/gpx.studio#22]
I ended up with a reference to a custom overlay that no longer exists. 

![image](https://github.com/user-attachments/assets/f60f1492-8248-44d7-82dc-59dc6265970d)

Even after deleting all custom layers and refreshing the webpage I still have that orphaned entry. 

I tried to reproduce the issue from scrath in a google chrome guest account but I am unable to nail it down.

**Comment by nevvkid** [comment]
@pfbreton-perso I think the same happened to me adding a layer accidentally as "overlay" and switching to "basemap" and again back to "overlay". The orphaned layer stays in the list of "Basemaps" and can't be removed. 
<img width="360" alt="image" src="https://github.com/user-attachments/assets/c0a831b7-92b0-4cf5-9738-0d4396b33e84">
<img width="279" alt="image" src="https://github.com/user-attachments/assets/8319ebb8-edcd-427a-b46b-66098e0e5bc1">

I am also on latest Chrome on MacOs.

**Comment by vcoppe** [comment]
Thank you for reporting this, and providing steps to reproduce the issue.
There were indeed issues when updating an existing custom layers, which I think I fixed now.
If you still have those "orphaned" layers in your browser, I think creating new custom layers will overwrite them (or you can simply clear IndexedDB data from the website but you will lose all your settings).

**Comment by nevvkid** [comment]
@vcoppe I will test today. Wondering if you got my Email?
