### ISSUE TITLE
"Close / Close All" menus

### ISSUE THREAD

**Issue by Volodymyr-13** [gpxstudio/gpx.studio#3]
I'd like to see a "Close / Close All" menus, so I can close selected gpx or all at once. 

![Screenshot](https://github.com/gpxstudio/gpx.studio/assets/3391456/64068c2d-598b-4631-b4d2-9e1fdb72b227)

**Comment by vcoppe** [comment]
What do you mean by closing? In the 'Edit' menu, you have the 'Delete' and 'Delete All' buttons. Is that what you are looking for?

**Comment by Volodymyr-13** [comment]
> What do you mean by closing? In the 'Edit' menu, you have the 'Delete' and 'Delete All' buttons. Is that what you are looking for?

Ah, I didn't saw that, but because it's not logically correct to have menus like that. 
This should be typical menus for working with files, since it is working with files. 
So, I'm expecting: 

 
![Screenshot](https://github.com/gpxstudio/gpx.studio/assets/3391456/07107f63-40ba-48b1-b69b-72019cd4ce29)

**Comment by vcoppe** [comment]
Delete buttons are usually in the 'Edit' menu, at least that's what I observed in the programs on which I based the interface. Here is some advice from ChatGPT:

> Me: I have a menu bar with items 'File', 'Edit', 'View', 'Settings', etc. In which submenu should the 'Delete' button appear?
> 
> ChatGPT: The 'Delete' button should typically appear in the 'Edit' submenu. The 'Edit' menu commonly includes options related to modifying content, such as Cut, Copy, Paste, Undo, Redo, and Delete. This placement aligns with user expectations and standard user interface design conventions.

Another reason for this is that you can use this button to delete things that are inside GPX files if you open the vertical file view. So it makes much more sense as it is because it does not only concern files.

**Comment by Volodymyr-13** [comment]
For sure, the chat will answer this because you are asking the wrong thing initially and overall.

Your mistake is that you named this action as “**Delete**,” which is incorrect. 
You open a file, so it should be **Open** (by the way, it is currently named “**Load**,” which is also non-conventional as per any other app). 
Then, why would you **Delete** the file? This implies a file action, meaning the file will be **deleted** from the **disk**, which is **confusing**, especially when placed in the “**Edit**” part. 
No, you should just “**Close**” the file, just as in any other app, when you finish working with it. 

Again, this is just a gold standard to have something like this and good UI/UX:

![Screenshot 1 Small](https://github.com/gpxstudio/gpx.studio/assets/3391456/18b3a9b0-e2a8-48d5-ac2d-f106b9ff75d2)![Screenshot 2 Small](https://github.com/gpxstudio/gpx.studio/assets/3391456/a2200a13-1067-491d-bc88-10b4bdbea362)

**Comment by Volodymyr-13** [comment]
> Another reason for this is that you can use this button to delete things that are inside GPX files if you open the vertical file view. So it makes much more sense as it is because it does not only concern files.

And this should not be shared with the same action, again UI/UX bad design. 
So, in "**Edit**" this is a nice place for a "**Delete**" command, but I'd named it with some explanations maybe like "**Delete** **Track**" or something. But **Close** is **Close** and it's only can be in **File**.

**Comment by IdrissaD** [comment]
I think it's more appropriate to use `Close` than `Delete` for the action of closing a file tab, and I think that conflating this option with the actual deleting of a route/track inside a file is confusing two very different concepts (at least in user mind, even if code-wise it surely isn't that different).

I don't think putting `close` in one of the top menus is the right thing to do. Why not putting a cross in front of every file tab for closing a tab/file? It's the way VSCode works and I find this way more intuitive. The cross of the focus tab could be visible at all time, and crosses of non-focused tabs could become visible on mouse hover. So users would have two options: either right-clicking on the tab, either directly clicking on the cross.
VSCode also has a `Close tab` in the `File` menu, but I don't think the added visual/UI clutter is worth it if you already can close a tab by two different means.

For closing all the tabs, I agree an option in the `File` menu seems more appropriate than in the `Edit` menu, for me `Edit` is a menu applied for file contents, not files themselves.

**Comment by vcoppe** [comment]
You can check the updated menus, it should now be like you expected.
The only annoying thing is that `Ctrl/Cmd+W` is a reserved shortcut to close browser tabs so I kept `Ctrl/Cmd+Delete`, which feels quite natural for me. Let me know if you have another idea.
