### ISSUE TITLE
Keyboard shortcuts clash with Safari default shortcuts

### ISSUE THREAD

**Issue by N3XT191** [gpxstudio/gpx.studio#31]
On MacOS (tested in Safari), all shortcuts are labeled in the menus with the command-key.

But to actually use them, you need to use the Control-key. 

So for example for the vertical file list, the command is ctrl-L, and not command-L like the dropdown say.

<img width="197" alt="Screenshot 2024-07-26 at 10 05 15" src="https://github.com/user-attachments/assets/37712ae1-3756-4f46-9393-351f2867f8bb">

This is also likely the cause for issue #29 (since the user isn't actually running the gpxStudio command, they'd need to press ctrl-Z for undo...)

I think CTRL is fine for Mac users. It's a little unusual but the advantage is that there's no chance for clashes with the system commands. But it should definitely be labeled correctly in the dropdown menus...

**Comment by N3XT191** [comment]
Perfect, thanks! I don't really care which way it is, as long as the labels in the dropdown menus actually work :)

**Comment by Volodymyr-13** [comment]
> All shortcuts are implemented for both Ctrl and Cmd combinations. Shortcuts with Cmd work for all browsers except Safari, unfortunately. Since this issue is limited to one browser, I think I will simply change the labels for Safari and keep the logic as it is.

Current http://gpx.studio works well, this should be Cmd + Z and all other keys.. but you killed it in favor of windows? Thats totally step back and from now I don't want to use "new" studio. I hope old one will just be online and works..

**Comment by Volodymyr-13** [comment]
> I think CTRL is fine for Mac users. It's a little unusual

This is totally fully not understanding what macOS is! @vcoppe I hope you re-fix this! Pls revert back to old gpx studio mode!

**Comment by vcoppe** [comment]
Cmd shortcuts work for all browsers except Safari.

**Comment by Volodymyr-13** [comment]
> Cmd shortcuts work for all browsers except Safari.

I just don’t understand.. since old gpx studio works perfectly in macOS as it should. 
Why you drop Safari support then if it worked and works currently for old version?

**Comment by Volodymyr-13** [comment]
@vcoppe too bad... no fixes now... so I'm not using it and will never use in future, until this will be working same as in current http://gpx.studio so just as should be for macOS.. 

What you've done now - DEAL BREAKER.
