### ISSUE TITLE
Loading GPX file fails in new app on iPad 

### ISSUE THREAD

**Issue by cajhanselaar** [gpxstudio/gpx.studio#37]
iOS 17.5.1

Both single file and batch upload fail on iOS. No error is thrown. No progress is shown. Process seems fine from a user perspective: I can choose open file, at which point I get the iOS file manager to choose photo library, take photo or choose file. Following steps I can successfully select a file for upload. 
there is no difference seen when the file is in the cloud, or is already downloaded.

**Comment by vcoppe** [comment]
Which browser are you using?
On Chrome, you can inspect error logs at the following URL: chrome://inspect

**Comment by vcoppe** [comment]
Closing the issue due to lack of information, feel free to comment here, I will reopen it if needed.
