### ISSUE TITLE
Fail to open WebGL on Mozilla Firefox

### ISSUE THREAD

**Issue by IdrissaD** [gpxstudio/gpx.studio#4]
OS: Windows 10 Professionnel 22H2
Browser: Mozilla Firefox
Version: 127.0 (64 bits)

**Steps to reproduce:**
Open https://gpx.studio/gpx.studio/

**Bug:**
All the map zone appears pitch black

![image](https://github.com/gpxstudio/gpx.studio/assets/73114156/b907ea8e-6b89-423f-9e9c-33b13515d112)

**Logs:**
```
Failed to create WebGL context: WebGL creation failed: 
* AllowWebgl2:false restricts context creation on this system. () [3.CSGOU326.js:2115:7080](https://gpx.studio/gpx.studio/_app/immutable/nodes/3.CSGOU326.js)
Error: Failed to initialize WebGL
    Immutable 13
    <anonymous> https://gpx.studio/gpx.studio/:43
    promise callback* https://gpx.studio/gpx.studio/:42
[3.CSGOU326.js:1:91545](https://gpx.studio/gpx.studio/_app/immutable/nodes/3.CSGOU326.js)
Uncaught (in promise) Error: Failed to initialize WebGL.
    Immutable 12
    <anonymous> https://gpx.studio/gpx.studio/:43
    promise callback* https://gpx.studio/gpx.studio/:42
```

I don't know if it's a browser or gpx.studio bug

**Comment by vcoppe** [comment]
> `AllowWebgl2:false restricts context creation on this system`

You need to check your browser parameters.
I should probably add a message if WebGL2 is disabled, and maybe set up a fallback.

**Comment by IdrissaD** [comment]
Thanks, fixed with the help of this page : https://www.yannkozon.com/blog/2161-comment-activer-webgl-dans-chrome-firefox-et-safari/

> Type `about:config` in the search bar
> Search `webgl.force-enabled` and change its value to `true`
> Search `webgl.disabled` if the value exists and change it to `false`

At least a warning would be a good idea!
