### ISSUE TITLE
Elevation Profile suggestions: rename view, option to disable elevation, don't open slope by default, zoom

### ISSUE THREAD

**Issue by SVNKoch** [gpxstudio/gpx.studio#40]
At the bottum there is the "View > Elevation Profile" UI.

- I would like to be able to disable the elevation graph and only plot the speed for example.
  Therefore this menu should be renamed to something like "Data Graphs"
- Currently when you disable and reenable the view (View > Elevation Profile), then "Show slope data" is automatically enabled.
- Add the option to zoom in this graph

**Comment by vcoppe** [comment]
> Currently when you disable and reenable the view (View > Elevation Profile), then "Show slope data" is automatically enabled.

This should be fixed now.

> Add the option to zoom in this graph.

I have created a new issue for this specifically.

> I would like to be able to disable the elevation graph and only plot the speed for example. Therefore this menu should be renamed to something like "Data Graphs".

I don't plan to do this for now because I have organized every other data source around the elevation data in the code, and I don't think that the elevation data is really in the way when you want to analyze the speed.
