### ISSUE TITLE
Feature Request: View Coordinates

### ISSUE THREAD

**Issue by Sklyvan** [gpxstudio/gpx.studio#45]
I think it will be really useful (and I think it is not really hard to implement) that when I click a point on my route, along with the "Start loop here" and "Delete" options, it displays the latitude and longitude coordinates of the point.

**Comment by nevvkid** [comment]
@Sklyvan not sure if that works for you. But you could just use the "Point of Interest" tool to find the coordinates.

<img width="469" alt="image" src="https://github.com/user-attachments/assets/3aab3fe6-cfbf-4d35-859e-d790f5fb4de4">

**Comment by Sklyvan** [comment]
Thanks, I will use that.
