### ISSUE TITLE
[Bug] - Time Tool: Incorrect Time calculations when entering Speed

### ISSUE THREAD

**Issue by dallinjared** [gpxstudio/gpx.studio#46]
Looks like a possible unit conversion issue. For Imperial, a 1 Mile Route @ 1 mph is calculating 2:35:31 when it should be 1:00:00. Metric properly calculates a 1Km Route @ 1 kph for 1:00:00.

<img width="1225" alt="Screenshot 2024-07-31 at 4 40 30 PM" src="https://github.com/user-attachments/assets/3a72c9af-9c7e-488c-8376-c9c0ed5e76ac">

**Comment by vcoppe** [comment]
Thanks for reporting this issue, it should be fixed now :)
