### ISSUE TITLE
Not able to access context menu on anchor point

### ISSUE THREAD

**Issue by abko** [gpxstudio/gpx.studio#52]
I am using the latest Safari release on macOS. When in Routing mode I am trying to open the context menu to do a split. Unfortunately the context menu does not appear on new anchor points (new ones that appear under my cursor), they do appear on already visible anchor points, but the split option is not (yet) present. 

This works fine with the original version. I am not sure if this is a known limitation of the current version or a bug. I decided to share it anyway.

Another small remark. On a Mac Ctrl-Z to undo is less natural than using Command-Z. It would be nice to use Command-Z when on a Mac.

Fantastic tool by the way. I always use it to merge Mountainbike tracks that can be found on mtbroutes.nl.

Thanks for all the good work. The new version even looks nicer than the previous one.

Kind regards, Abko

**Comment by vcoppe** [comment]
Splitting and cropping files can now be done with the "Scissors" tool, and no longer within the routing tool.

If you use any other browser than Safari, all shortcuts are displayed with Command. Unfortunately, some shortcuts with Command clash with some native Safari ones.

**Comment by abko** [comment]
Ah, great. Sorry, I should have noticed ;-) Fantastic App. Thanks @vcoppe  for the great work !!
