### ISSUE TITLE
Zoom on elevation profile to analyze long routes

### ISSUE THREAD

**Issue by vcoppe** [gpxstudio/gpx.studio#54]
Extracted from #40

**Comment by nevvkid** [comment]
Maybe as an inspiration for this. A feature I use a lot on tour in MapOut is that i can select a track / route and slide on it to define the start "A" and end "B" point of my selection. This renders the elevation profile and statistics for the selection - what you already have implemented besides the zoom. I quite like that I don't need to get into an "edit mode" like in komoot. And can just do this on every route in my canvas.
![image](https://github.com/user-attachments/assets/3ca31894-61e5-4adb-93f3-b0c4871969f5)

But maybe the zooming from the whole elevation profile to the elevation profile of the selection you can checkout on komoot. While the representation of the slope color coding is nicer in gpx.studio - not just shown on the edge of the profile but on the full profile. 
<img width="1092" alt="image" src="https://github.com/user-attachments/assets/369dbdc4-b772-4c01-9691-3f8e72679b0b">
