### ISSUE TITLE
[Feature Request]  highway profile

### ISSUE THREAD

**Issue by drazde** [gpxstudio/gpx.studio#65]
Like slope and surface profiles, could be useful have type of **highway**.
When I plan a route I considerating km on track and on path. Km on path could be more difficult than on track for MTB

**Comment by vcoppe** [comment]
I just added this. Feedback on the colors is welcome.

**Comment by drazde** [comment]
At the end of the hike, I complete the Openstreetmap map with hike and mtb scale. I think it's great to have this information, but the information all together could be confusing

![immagine](https://github.com/user-attachments/assets/92cbff59-c179-45c1-b6b6-11f3d2cd7376)
