### ISSUE TITLE
Crop/split tool breaks interface if activated while a track is selected

### ISSUE THREAD

**Issue by hyOzd** [gpxstudio/gpx.studio#67]
How to reproduce:

- Draw a track with the new gpx studio app
- Make sure the track is selected (if you have just drawn, it should be selected)
- Click the 'Crop or Split' tool
- Crop tool activates but its popup menu doesn't appear. Clicking on the track splits it but second part doesn't appear. Menu and tool buttons become inaccessible. Refreshing the page restores the state and second part appears.

Note: If no track is selected crop tool behaves correctly. It simply expects me to select a track before working. It splits the track as I expect and nothing breaks. But if I start a crop operation while a track is selected, situation that I described above happens. I'm not sure if there is a way to unselect a track simply. I found that I can create a new track and close it and this results in a no track selected state.

Browser: Firefox 129, Linux. I've reproduced the problem on Chromium as well but it only happened after a few tries.

**Comment by vcoppe** [comment]
Unfortunately I am not able to reproduce this (tried Firefox and Chromium).
Could you maybe look into the Javascript console and share the error logs?

(You can deselect a file with Ctrl/Cmd+Click)

**Comment by hyOzd** [comment]
From firefox 129:

These messages were in my console before:
```
WEBGL_debug_renderer_info is deprecated in Firefox and will be removed. Please use RENDERER. index.C62KPXWc.js:24:43089
WebGL warning: texImage: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads. 32
After reporting 32, no further warnings will be reported for this WebGL context.
InstallTrigger is deprecated and will be removed in the future. index.C62KPXWc.js:23:88834
MouseEvent.mozPressure is deprecated. Use PointerEvent.pressure instead. index.C62KPXWc.js:11:165716
MouseEvent.mozInputSource is deprecated. Use PointerEvent.pointerType instead. index.C62KPXWc.js:11:165716
```

This error message is printed as I activate the 'crop tool' by clicking on the toolbar icon:

```
Uncaught (in promise) TypeError: this.local.points[u] is undefined
    Immutable 33
index.C62KPXWc.js:2125:76242
    Immutable 9
    forEach self-hosted:160
    Immutable 3
    forEach self-hosted:160
    Immutable 2
```

I also looked at  chromium console ( v112), maybe it's message is more helpful:
```
index.C62KPXWc.js:2125 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'time')
    at Vc.slice (index.C62KPXWc.js:2125:76281)
    at fe (index.C62KPXWc.js:2666:14071)
    at MU.r.$$.update (index.C62KPXWc.js:2666:14865)
    at jt (index.CWl_xw7W.js:4:3914)
    at new r8 (index.C62KPXWc.js:2666:15061)
    at Array.ke (Toolbar.OuSj28an.js:1:8480)
    at Array.Se (Toolbar.OuSj28an.js:1:9359)
    at Nt (scheduler.BYRXjsd2.js:1:1149)
    at k (card-content.DqJsLHIb.js:1:1195)
    at jt (index.CWl_xw7W.js:4:3960)
slice @ index.C62KPXWc.js:2125
fe @ index.C62KPXWc.js:2666
MU.r.$$.update @ index.C62KPXWc.js:2666
jt @ index.CWl_xw7W.js:4
r8 @ index.C62KPXWc.js:2666
ke @ Toolbar.OuSj28an.js:1
Se @ Toolbar.OuSj28an.js:1
Nt @ scheduler.BYRXjsd2.js:1
k @ card-content.DqJsLHIb.js:1
jt @ index.CWl_xw7W.js:4
H @ card-content.DqJsLHIb.js:1
Ce @ Toolbar.OuSj28an.js:1
Nt @ scheduler.BYRXjsd2.js:1
K @ card-content.DqJsLHIb.js:1
jt @ index.CWl_xw7W.js:4
G @ card-content.DqJsLHIb.js:1
_t @ Toolbar.OuSj28an.js:1
p @ Toolbar.OuSj28an.js:1
mt @ scheduler.BYRXjsd2.js:1
dt @ scheduler.BYRXjsd2.js:1
Promise.then (async)
_t @ scheduler.BYRXjsd2.js:1
ht @ index.CWl_xw7W.js:4
(anonymous) @ index.CWl_xw7W.js:4
(anonymous) @ 5.BKzStSnS.js:1
c @ paths.C-Pme1Eg.js:1
l @ paths.C-Pme1Eg.js:1
i @ Toolbar.OuSj28an.js:1
(anonymous) @ scheduler.BYRXjsd2.js:1
ae @ scheduler.BYRXjsd2.js:1
G @ index.C62KPXWc.js:2666
(anonymous) @ scheduler.BYRXjsd2.js:1
ae @ scheduler.BYRXjsd2.js:1
J @ index.C62KPXWc.js:11
```

Note that Chromium started with these messages but I don't think they are related:
```
events.mapbox.com/events/v2?access_token=pk.eyJ1IjoidmNvcHBlIiwiYSI6ImNseWlrYXo0cjBocW0ya3F5MGtwM3A1b28ifQ.25xwq1HN121RHqM_zkWweQ:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
```

**Comment by hyOzd** [comment]
I noticed that problem doesn't occur with a track file that I recorded with osmand app and loaded into gpx studio. It only happens with a track that is created in gpx studio.

**Comment by vcoppe** [comment]
It was actually only happening for very short files so that's why I didn't manage to reproduce it first.
Thank you for reporting this and providing debug information! It should work as expected now.

**Comment by hyOzd** [comment]
Thanks for the quick fix.
