### ISSUE TITLE
Ctrl-backspace shortcut to close a file conflicts with common 'delete word' shortcut

### ISSUE THREAD

**Issue by hyOzd** [gpxstudio/gpx.studio#68]
When editing any text such as track name, POI description etc, if I try to *delete a word* with CTRL+Backspace shortcut it _deletes the track_ instead. AFAIK this is a very common shortcut on linux UIs. It works almost everywhere. Maybe conflict can be solved by disabling 'delete track' shortcut when editing text or when a popup form is open.

**Comment by vcoppe** [comment]
This should solve your issue

**Comment by hyOzd** [comment]
Thanks for the fix.
