### ISSUE TITLE
Points of interest layer

### ISSUE THREAD

**Issue by N3XT191** [gpxstudio/gpx.studio#7]
I used this feature a lot when planning my hikes. Would be a shame to lose it!

New version:
<img width="296" alt="Screenshot 2024-07-15 at 17 39 26" src="https://github.com/user-attachments/assets/5bc5c945-3896-4da9-a01f-d0e789021068">

Old version:
<img width="163" alt="Screenshot 2024-07-15 at 17 41 31" src="https://github.com/user-attachments/assets/ced0127c-d57e-4b6f-99d8-7eab64fa98e2">

**Comment by vcoppe** [comment]
You can go check out the website 🥳 (c8a8ff7)
By the way, let me know if there are other POI types that you would want to see.

**Comment by N3XT191** [comment]
Wow, that was really quick, thank you!

For my hikes, I'm interested in anything that provides, shelter, water or food, so this would be the POIs I've used in the past:

<img width="180" alt="Screenshot 2024-07-18 at 08 52 19" src="https://github.com/user-attachments/assets/a24efecd-5be1-4d25-81a1-2ec5e308f6fa">

I don't really care about the differentiation of pub and bar, or hotel and hostel or water point/water spring, I just like to see the complete list of options where I could go if I needed food/water/shelter.

**Comment by vcoppe** [comment]
I have indeed merged some categories, both to group the Overpass queries and to simplify the UI.
For example, the new "Accommodation" category groups the previous "Hotel", "Hostel", "Guest House", "Motel", "Campsite", "Alpine Hut" and "Wilderness Hut" ones.

**Comment by IdrissaD** [comment]
I'm all for merging some categories, but I feel like it's a bit too wide of a merge. An hotel and a wilderness hut really don't have anything in common, and as your app is widely used by outdoor enthusiasts, it's a key difference. I believe you should have three categories:
- Hotels & al. : hotel, hostel, guest house, motel
- Campsite
- Huts: alpine hut, wilderness hut

I believe it would still be pretty simple, but much more accurate for users. For the moment, I have to click on each POI to see if it's a hotel or a wilderness hut, which are radically different types of "accomodation".

**Comment by vcoppe** [comment]
I may have merged a bit too much indeed 😅 I just updated the website with your suggestions.
Concerning the categories that do not appear, you can activate them in the map layer settings.

**Comment by IdrissaD** [comment]
Oh yes, I didn't see that the option to add more layers was moved to the settings tab! From my point of view POIs are perfect as they are now, thans for your legendary reactivity as always! ;)
