### ISSUE TITLE
Contextual menu is undiscoverable

### ISSUE THREAD

**Issue by mbof** [gpxstudio/gpx.studio#73]
This may be working as intended, feel free to close out — just a suggestion.

The first time I used GPX Studio, it took me a while to figure out how to change the appearance of a track, until I had the idea to two-finger tap on the title of the track.

The lack of an obvious affordance could be a usability challenge for some users. A cheap fix would be to add a recognizable menu entry point such as a vertical ellipsis icon ("kebab") next to the label.

<img width="318" alt="image" src="https://github.com/user-attachments/assets/8a84ff5e-1a52-4b58-b1d6-22f2c4ac1fba">

**Comment by vcoppe** [comment]
The actions shown in the context menu can all be accessed through the "Edit" menu. Therefore, I am not for adding a visual hint to the interface.

I am closing this but feel free to comment with alternative suggestions if you think of another way to make this clearer.
