### ISSUE TITLE
no slope data on loaded gpx 

### ISSUE THREAD

**Issue by m4ri0g** [gpxstudio/gpx.studio#79]
occassionally there is no elevation data show on loaded gpx,, loading data in strava or komoot shows the elevation profile

![image](https://github.com/user-attachments/assets/9137db4e-bc09-4b4a-9731-cbda31fff71a)

**Comment by vcoppe** [comment]
This happens if your file does not contain any elevation data. You can add it here: https://www.gpsvisualizer.com/elevation.
Ideally, I would like to add something to do this within gpx.studio but have not found the right way yet.
