### ISSUE TITLE
🐛 New site doesn't snap view to area of uploaded GPX file

### ISSUE THREAD

**Issue by tarfeef101** [gpxstudio/gpx.studio#8]
The old site's behaviour was, when you upload a GPX file, to snap the map view to that region. However, on the new site, when one uploads a file, the map stays in-place at the location it opened to, even if the uploaded file isn't visible at all. I think the former behaviour is probably superior, and intended

**Comment by vcoppe** [comment]
What you mention is the behavior that I implemented, and it works on my laptop.

Does this occur with any GPX file you try to load? Do they contain only points of interest?

**Comment by vcoppe** [comment]
Can you try again now?

**Comment by tarfeef101** [comment]
does seem to be working now, yeah
