### ISSUE TITLE
Regression: Elevation is not added to the track.

### ISSUE THREAD

**Issue by snooppr** [gpxstudio/gpx.studio#82]
I write a gpx track for hours, after importing the track to a local file, the altitude is always missing in the track. After importing such a track to GPX Studio, the altitude was created automatically and I exported such a track. This worked a few days ago. Now it does not work. Should I wait for a fix or immediately look for analogs (repository [archived](https://github.com/gpxstudio/gpxstudio.github.io))?

![1](https://github.com/user-attachments/assets/79e1ac03-5507-4232-af82-a3524ecbe743)
https://gpx.studio/

**Comment by snooppr** [comment]
Sorry, I saw the proposed solution late https://github.com/gpxstudio/gpx.studio/issues/79#issuecomment-2325808703
This solution does not work. After adding the height to the track, it completely removes the recorded heart rate from the track.

Previously, the height was always added to the track automatically, I used it for a long time. The last time was August 31 and gpx studio worked fine. But you write in that comment that you did not find a suitable way, how did it work before??

**Comment by vcoppe** [comment]
I've added a new tool to add elevation data.
I had removed this feature mainly because some users were loading huge files without elevation data, which caused the website to freeze. So now, it has to be triggered manually, which can also be useful in other cases.
