### ISSUE TITLE
Keyboard shortcuts are broken and this is DEAL BREAKER for macOS

### ISSUE THREAD

**Issue by Volodymyr-13** [gpxstudio/gpx.studio#88]
I just see this new gpxtsudio is like windows targeted? 

First I created ticked about Command+Z for Undo/Redo and it was ignored. https://github.com/gpxstudio/gpx.studio/issues/31#issuecomment-2282228115

Now I see that who developing this, fully don't understand that  F1-F4 for example will not work, because of macOS keys and functions. 
And all these **Ctrl** windows key stuff just a fail. Undo/Redo is NOT working as it worked before in old gpx.studio.

Looking for alternatives..

![Screenshot](https://github.com/user-attachments/assets/a48bdea6-bb55-40d1-82fe-2c187d0df8c8)
![Screenshot 1](https://github.com/user-attachments/assets/f2662cfb-248c-41b9-bbf5-beea08c82790)

**Comment by vcoppe** [comment]
Browsers have reserved shortcuts that websites cannot override.
Sadly, this set of reserved shortcuts differs from one browser to another, and Safari is the most annoying of them.
As I mentioned before, if you open gpx.studio with Firefox or Chrome, <ins>all Cmd-based shortcuts work</ins>.

Here are the shortcuts that clash with Safari ones:
- Cmd+O for opening GPX files: this triggers the "open file" of Safari
- Cmd+H for hiding the selection on the map: this hides the window
- Cmd+L for toggling the vertical/horizontal layout: this focuses the address bar

F1-F5 shortcuts can be accessed by pressing `fn` on MacOS.

If you have good suggestions on other key combinations to use for each of these actions, I can still change them and show Cmd-based shortcuts for Safari. Although it won't be very intuitive to set something else than Cmd+O to open files.

That being said, the tone of the comments you made across multiple issues is far from constructive and certainly does not encourage me to consider any of your requests. If you want to keep contributing to this project with your ideas, please adopt a friendlier tone, give a factual analysis of the problems you are encountering, and provide concrete suggestions on how you would fix a given issue or improve some aspect of the project. Thank you for your understanding and cooperation.

**Comment by Volodymyr-13** [comment]
And how about https://pixlr.com/editor/ which I'm using daily and which works flawlessly on macOS and Safari.
It feels like a native app running, with all keyboards shortcuts support, undo/redo and other like open/save file... and more.
But sometimes its like not overrides Cmd+O, I can confirm that, looks like when I just switched tab, it could open a Safari operation, but then when I click anywhere on a page, its like steal that command and then will open file to pixlr. 

> F1-F5 shortcuts can be accessed by pressing fn on MacOS.
I've disabled this, since this is AWKWARD when I just want to press a F1 to change brightness immediately, so I don't have to press something else. 

![Screenshot 2](https://github.com/user-attachments/assets/71e7490d-235c-4f09-9a7a-98e7aa892df5)

My English is rly not good, perhaps I should try to use chatgpt to rephase everything... I'll try next time :)

**Comment by vcoppe** [comment]
> And how about https://pixlr.com/editor/ which I'm using daily and which works flawlessly on macOS and Safari.

I have never used this website so I don't really know the shortcuts.

Here is another example: https://www.photopea.com/.
You can see that Cmd+O is the shortcut to open a file from your desktop, however it doesn't work on Safari because the file is opened by the browser instead of the website. This is something we can unfortunately not override.

So either we can leave Ctrl-based shortcuts for Safari, or we need to change the three shortcuts below to something not reserved by Safari.

> Here are the shortcuts that clash with Safari ones:
> 
> - Cmd+O for opening GPX files: this triggers the "open file" of Safari
> - Cmd+H for hiding the selection on the map: this hides the window
> - Cmd+L for toggling the vertical/horizontal layout: this focuses the address bar
> 
> If you have good suggestions on other key combinations to use for each of these actions, I can still change them and show Cmd-based shortcuts for Safari.

**Comment by Volodymyr-13** [comment]
@vcoppe 
**photopea** works well the same as pixlr in my Safari, when I press Cmd+O, but again in the same way of pixlr, could be not from the first time, since you have to focus not just a tab but a page, so click somewhere or just working in it. Mostly it's working... or at lest working after a 2nd try.

**Comment by Volodymyr-13** [comment]
There is some hack I think, which both these sites are doing, since it's working for me, but not always, yes, not ideally, but I'm not really noticing this. The most important is Undo/Redo which is working 100% all the time. 

Looks like they also shows this a bit differently, but still working in the same way..

![Screenshot](https://github.com/user-attachments/assets/e7f8de5a-f51c-4501-aa25-7607b508b707)
![Screenshot 1](https://github.com/user-attachments/assets/536e39d2-67f5-4612-a85d-99fe7550f4c9)
![Screenshot 2](https://github.com/user-attachments/assets/255a7345-4860-40c8-9c1e-95444e7c2cb9)
![Screenshot 3](https://github.com/user-attachments/assets/5b2c1b31-aad3-42ce-a1e1-3488ec9148ed)

**Comment by vcoppe** [comment]
I have searched for a hack multiple times, and cannot find any.
You can try things yourself, all the shortcuts are handled in `website/src/lib/components/Menu.svelte`, see here for the Cmd+O: https://github.com/gpxstudio/gpx.studio/blob/08ad9b4186290f202ae84812fe18fea8c44add2f/website/src/lib/components/Menu.svelte#L532-L534

**Comment by Volodymyr-13** [comment]
Unfortunately I'm not a web guy) only Swift a little bit.. perhaps chatgpt 4.0 or so could help)? Since I can just share sites where this is happening, so thats why I speaking loud about this in general)

**Comment by vcoppe** [comment]
It's not working for me on these websites. So I think the only option is to find other shortcuts instead of:
- Cmd+O for opening GPX files
- Cmd+H for hiding the selection on the map
- Cmd+L for toggling the vertical/horizontal layout

**Comment by Volodymyr-13** [comment]
Perhaps like https://pixlr.com/editor/ doing is the best case.. but they also supporting both keys for Undo/Redo, and for other shortcuts..

**Comment by vcoppe** [comment]
> Perhaps like https://pixlr.com/editor/ doing is the best case.

But all shortcuts are shown with Ctrl, just like what I did 🤷‍♂️
You can also use Cmd on gpx.studio but the shortcuts I mentioned will not work.

**Comment by Volodymyr-13** [comment]
> ….. but they also supporting both keys for Undo/Redo, and for other shortcuts..

Both keys, I mean so it’s working for any. I can normally use Undo/Redo in it, but not on gpx.studio, so looks like that’s a part of this “hack” or just idea overall.. to make it work anyway.

**Comment by vcoppe** [comment]
So, is it okay like this for you?

**Comment by Volodymyr-13** [comment]
Welp, looks like for Undo/Redo - yes. 
I was also thinking why just not use “O” key for open? And so on. As additional key for Safari, but still show in menu like pixlr does.

**Comment by vcoppe** [comment]
I am not really for adding shortcuts that are not explicitly shown in the interface.
The current shortcuts are intuitive and work for all combinations of OS and browsers, except for MacOS+Safari where Ctrl is shown instead of Cmd, so I don't think it's necessary to add more complexity to this.

**Comment by Volodymyr-13** [comment]
@vcoppe all right, but also, for example TikTok on Safari steals all these keys easily https://www.tiktok.com/@shtefan_01/video/7415866177961954566 

But this not 100% always working, but it's working when you open page first time at least. 
Cmd+O, Cmd+H, Cmd+L, Cmd+W disabled on TikTok pages. Or used as it own commands.
