### ISSUE TITLE
How to create a new route when one is already selected?

### ISSUE THREAD

**Issue by pdonias** [gpxstudio/gpx.studio#91]
The route edition tool is very nice but when a file is selected, I don't know how to create a new one from scratch. It works when no file is selected so maybe I'm just missing a way to unselect everything? The only workaround I found is to refresh the page.

Sorry if I'm missing something obvious :)

**Comment by vcoppe** [comment]
To create a new file: "File" -> "New".
To deselect a file, you can Ctrl/Cmd+click on it.
You can find all of that in the documentation: https://gpx.studio/help.

**Comment by pdonias** [comment]
Thanks for the answer! Indeed, I missed the "File > New" option, that works. However, I did try Ctrl+click to unselect a file but it doesn't seem to work on my side. I'm on Linux and I tried on Chrome and Firefox.

**Comment by vcoppe** [comment]
I just realized there was an issue with Ctrl+clicking directly on the line.
Now you can either Ctrl+click on the file tab, or on the line on the map.
Can you confirm it works for you?

**Comment by pdonias** [comment]
I just tested, it does work if I Ctrl+click on the line, but it doesn't work if I Ctrl+click on the file tab.

**Comment by vcoppe** [comment]
There was also an issue with this for non-Mac users. Can you try again?
I can't believe this feature was bugged since the beginning, it's so important to be able to select multiple files 😵

**Comment by pdonias** [comment]
It works now! :tada:
Thanks! :)

**Comment by vcoppe** [comment]
Cool, thank you for bringing this major issue to light!
